### ISSUE TITLE
Prepare for BWS Service Awareness event

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#149]
### Overview
We are partnering with BWS to onboard volunteers for community service hours and we need to plan our pitch, create presentation materials, assign speakers and attendees, and fill out all the paperwork sent by BWS by Monday, March 14th 12 pm PDT. BWS Service Awareness Day is scheduled for Tuesday, March 15th 2022 at 9 am PDT.

### Action Items

- [x] Plan our pitch
- [x] Create presentation
- [x] Figure out who will speak
- [x] Create script for presentation
- [x] Assign guest attendees
- [x] Ask for Zoom link for guest attendees
- [x] Fill out paperwork
- [x] Send paperwork and presentation slides to BWS by 12 pm on Monday, March 14th 2022

### Resources/Instructions

Folders:

- [Service Hours](https://drive.google.com/drive/folders/1LZUi6Kh4ed7grLmrtzzV8I9IPJuzahLD?usp=sharing)

***Note: Housed on new Service Hours Drive**

Drafts:

- [HfLA Service Hours Opportunity Presentation](https://docs.google.com/presentation/d/1mmnx0a82Vwpg28f_WE9LaKOyrKQbgZqly_bBSq5SJg0/edit?usp=sharing)

Resources sent by BWS:

- [Community Intake Form](https://docs.google.com/forms/d/e/1FAIpQLSdSb9O1bmy6uQNXg9kX9tH-gbiEQAZcI2i-h85M4b5DHGgT1Q/viewform?vc=0&c=0&w=1&flr=0)
- [Brentwood Guest Agreement](https://resources.finalsite.net/images/v1618326635/brentwoodca/z2j8qy1y1bynngz9sk4h/BrentwoodGuestAgreement.pdf)
- [Presentation Template](https://docs.google.com/presentation/d/1GPVxz5npCu9ZjFBuTyDpOh2AtmedLa6fsTa3dbjN-qc/edit#slide=id.ga073618e60_0_16)

**Comment by Rabia2219** [comment]
Grace needs a guest Zoom link to attend. Will wait for Jhamasa to send the new link to figure out if we need to ask for a Guest link or just forward the new link to Grace.

**Comment by Rabia2219** [comment]
@ExperimentsInHonesty if you have any feedback after the event...please comment here and then the issue can  be closed. Thanks

**Comment by ExperimentsInHonesty** [comment]
Notes from the event

### Items can be approved
- Form did not have workforce development in it, had to ask for it be added (was added promptly).
- 2 presenters, at the end, were cut for time
- BWS team, If they had orgs slide decks,  cut them themselves instead of asking the org to cut (one of the orgs got pretty upset)
- Original time invitation was 15 min, which got change to 5 min on Friday morning the week before, to 2 min the night before (8:30 pm)
- The run through that was scheduled for day of 8:45am (15 min prior) was not available
- No panelists could rename themselves because it was locked down (must be set in zoom general settings before meeting). 
-  Which required the one Host to do all the renaming.  Which led to people duplicating their asks if there were multiple people on a team, trying to watch out for their team members
- Assumed people understood that a panelist link should not be shared and didn't ask us to provide a list of all the people who would attend.  They could have provided the guest link for non-speaking attendees.
- zoom and calendar links were not setup early enough in the process
- If the students had experience with the non-profit, they were more effusive about their intros (minor issue)
- The participants were not told that their mission statement would be the introduction
- When Bonnie screen shared, she forgot to unmute for 5 seconds.

### What went well
The students read the intros well
We were in good company (other impressive non-profits)
It moved quickly, it was exciting and there were no draggy moments
The technical glitches were pretty much invisible to the attendees
Saw examples of other good presentations

### Suggestions for improvement
Add a timer to the screen
