### ISSUE TITLE
Setup Zoom Timer for meetings

### ISSUE THREAD

**Issue by gracieama** [hackforla/internship#162]
### Overview
We need to set up zoom timer for meetings so that we can timebox various activities.

### Action Items
- [x] Add links to the timers from Chrome marketplace
- [x] Review the features
- [x] Determine which one to try
- [x] Publish choice on internship wiki 
- [x] Add link to agenda
- [x] Add link and details to product management wiki

#### Works with meetings and webinar - FREE
- [Timer by Zoom](https://marketplace.zoom.us/apps/cXw5IXmqT6SIIBQxgM_PfQ)

#### Works with meeting and webinar - PAID
- [Meeting Timer, Agenda Timer & Clock Countdown by Blue Sky Apps](https://marketplace.zoom.us/apps/3Jdbzv64QnKYAT911tlV9Q) 

#### Notes
Does not work on a Chromebook, along with other features of zoom.  Although using the new [PWA](https://blog.zoom.us/how-to-use-zoom-on-a-chromebook/) might solve that.

### Requirements
- can be seen by people in the meeting
- has an audible alarm
- allows for screen sharing (i.e., if the timer only works by sharing the screen, then it's not useful)
- either minimal setup or one time setup
- is either free or has a one time charge, or the subscription is reasonable and can be used across multiple zoom accounts.

**Comment by ExperimentsInHonesty** [comment]
## Cloq

### What it does
- It counts down
- Once setup, you can add it to the agenda and use it over and over.
- It creates a custom URL that can be shared and reused (see example: https://cloq.digital/timer.php?id=scary-scarab-2021)
  - In order to have a different timer for each meeting you will need to reload the domain name https://cloq.digital, and it will create a new id.

### What it doesn't do
- It does not count up
- alarm setting is auto off and cannot be changed using the web interface

### Additional items to explore
- download the https://www.flotato.com/ app and then use the macOS version of the app to see if the alarm can be turned on and the timer still shared.

**Comment by Annie-Truong** [comment]
## Cuckoo Timer

### What it does
- It counts down (you can adjust the time) 
- Once setup, you can add it to the agenda and use it over and over
- It creates a custom URL that can be shared and reused (see example: https://cuckoo.team/Hi)
    - In order to have a different timer for each meeting, you will need to reload the domain name https://cuckoo.team/, create a session name and it will create a new shareable ID link)
- The timer goes off with an alarm sound

### What it does not do
- It does not count up

--> propose this tool in next PM meeting

**Comment by Rabia2219** [comment]
We used the Cuckoo timer during the intern onboarding. Haven't been using it much after that. Do we like it enough to add it to the Product Management Wiki?

**Comment by Rabia2219** [comment]
We have decided on Cuckoo and added it to the PM Wiki
