### ISSUE TITLE
Create Slide Deck for dissemination of research results

### ISSUE THREAD

**Issue by Aparna1Gopal** [hackforla/internship#250]
### Dependencies
- #329

### Overview

We need to create a slide deck template to be able to disseminate research results and insights to all internal and external stakeholders in order to communicate the value of this research. Stakeholders include the product owner, designers, mentors, mentees. 

### Action Items

- [ ] Identify the branding of TWE22 and decide on a Slide Deck design and format 
- [ ] Create a template to identify the narrative that will be used for the research findings
- [ ] Create slides for the categories
- [ ] Review with Research Lead
- [ ] Review with Product
- [ ] Update relevant WIKI page (See resources)
- [x] Check issue #208 to see if all sub-issues have been closed. If yes, close 208
- [ ] Release dependency on #322 and if it's the last dependency, move 322 to the new issue approval column

#### Categories
Project Introduction, Timeline, Types of Stakeholders, Overview of Research conducted, Methods used, Data Collection, Data Analysis, Overview of findings and insights, Research Impact and Next Steps. 

#### Other
- [TWE Template presentation](https://docs.google.com/presentation/d/1m7cYJ9jeH-z6bUv9xiHOjxmBUmANZrKs7YtQbNVfqgY/template/preview)
- Example [RP001 Research Analysis presentation](https://docs.google.com/presentation/d/1i83YamHc64eBGIjtkb9PJ-Gnhwkafo-uRFD0qjTZKWo/edit#slide=id.gea24f90547_0_3)
- UX Research Guides Templates https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates
- Create a Guide: Synthesizing Research https://github.com/hackforla/UI-UX/issues/46
- Guide: How to Present Your Work (UX Research) https://github.com/hackforla/UI-UX/issues/24
- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

**Comment by Aparna1Gopal** [comment]
**Updated following under Resources section:** 

UX Research Guides Templates https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates
Create a Guide: Synthesizing Research https://github.com/hackforla/UI-UX/issues/46
Guide: How to Present Your Work (UX Research) https://github.com/hackforla/UI-UX/issues/24

**Comment by ExperimentsInHonesty** [comment]
This issue needs to be cleaned up so that we can have a template for making an analysis template issue (which will require a deck template).

**Comment by priyatalwar** [comment]
We have added the following links to other:
- [TWE Template presentation](https://docs.google.com/presentation/d/1m7cYJ9jeH-z6bUv9xiHOjxmBUmANZrKs7YtQbNVfqgY/template/preview)
- Example [RP001 Research Analysis presentation](https://docs.google.com/presentation/d/1i83YamHc64eBGIjtkb9PJ-Gnhwkafo-uRFD0qjTZKWo/edit#slide=id.gea24f90547_0_3)

@bradyse Please take a look at these two links and see if some of the links that are listed in the other are unnecessary now

**Comment by bradyse** [comment]
@priyatalwar 

I have noted that this issue should be rewritten as a Research Template Issue for creating data presentations. I removed the link to the mentor roadmap issue. For whatever reason, that specific issue got changed and morphed into what it is now instead of new issues being created from it as a result. We know have a more streamlined roadmap template identified in our Research Wiki Template Page.

Once the new template issue has been created using [this template](https://github.com/hackforla/internship/issues/new?assignees=&labels=feature%3A+board+%2F+google+drive+%2F+tools%2C+feature%3A+missing%2C+milestone%3A+missing%2C+role%3A+missing%2C+size%3A+missing&template=create-a-template-issue.md&title=TWE%3A+Create+Template+Issue%3A+%5Bname+of+template%5D), we can close this issue.
