### ISSUE TITLE
Create Mentor Exit Survey

### ISSUE THREAD

**Issue by christine-el** [hackforla/internship#251]
### Overview
We need to create a mentor exit survey to administer to mentors during mentor offboarding in order to get feedback on what the mentoring experience was like and how the mentorship program can be improved upon on in the future.  

### Action Items

- [x] Draft a survey
- [ ] Discuss with UX lead and/or Bonnie
- [ ] Revise survey
- [ ] Update relevant WIKI page (See resources)

### Resources/Instructions
- [Research Plan 15: Mentor Exit Survey Wiki](https://github.com/hackforla/internship/wiki/Research-Plan-15:-Mentor-Exit-Surveys)
- [Research Plan 15 Google Drive](https://drive.google.com/drive/folders/1j17obDS6E5OeFrisUJPcFE77pavg1GSP)
     - [Research Plan Document](https://docs.google.com/document/d/1bHYxFmFTX0px0XkgPCXU_FiOQ34v4WFpECpipYrM3vo/edit?usp=sharing)

- Find WIKI page for your role [Internship Wiki, Join the team page](https://github.com/hackforla/internship/wiki/Joining-the-Team)

**Comment by bradyse** [comment]
@sniux and @christine-el, I put a[ draft of the survey and the research plan](https://docs.google.com/document/d/1bHYxFmFTX0px0XkgPCXU_FiOQ34v4WFpECpipYrM3vo/edit?usp=sharing) in the resources. Please let me know if these goals are in line with what you all were thinking.

@lkawentel, I included you on this comment so that you can be in the loop regarding alignment for the interview script. If my open-ended questions seem duplicative, please let me know.

Thanks!

**Comment by bradyse** [comment]
@christine-el @epierotti3 

Since the mentor exit surveys are now being rolled into the exit interviews, can we close this issue?

**Comment by epierotti3** [comment]
See issues #266 and #267 for updates related to this issue.

**Comment by Aparna1Gopal** [comment]
**Notes:** 

Relevant Issues: 
https://github.com/hackforla/internship/issues/265
https://github.com/hackforla/internship/issues/266
https://github.com/hackforla/internship/issues/267
