### ISSUE TITLE
IS22 Mentor Standup

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/internship#253]
### Overview
We need a place to take notes during the Mentor Standup and for the mentors to add their updates.

### Action Items

- [x] Roll Call
- [x] Take Notes (PMs)
- [x] Add updates (Mentors)
- [ ] Update relevant WIKI page (See resources)

```
Roll Call
- Dean
- Satya
- Jonathan
- Emerson

```
### Resources
- [TWE: End of Week Feedback from Mentor Survey](https://docs.google.com/forms/d/e/1FAIpQLSeR3ntOrFKh--Ni2xWwmAWiG2_jrY8K_pPB3wQSB7Cjs91aXA/viewform)

**Comment by Rabia2219** [comment]
Roll Call
- Satya
- Jonathan

**Comment by s4tya** [comment]
* Clayton and I met on Monday/meeting him again today in 10 mins
* Bonnie mentioned needing to let the interns know how important it is to communicate blockers early. Will bring that up with Clayton.
* We will possibly continue our relationship after 3 weeks.
* Need to have a catch-up meeting with Bonnie re: LinkedIn profile
* Could have joined the LinkedIn meeting on Tuesday even if I was delayed by 15 mins
* Reminder: I will be away on Wednesday-Friday next week but will leave async updates here.

**Comment by emecas** [comment]
Report: We meet with Tung 07/12/2022 for about 1 hour, mainly a session based on open dialog and active listening, attempting to address it toward her main goals, which we are also trying to identify and prioritize, hoping it is an ideal approach and is being useful for her.

Personally I am enjoying this approach, even more than mentoring teammates at work, it feels like more openness and less restrictive  for developing a good dynamic, building rapport, and ensuring that the climate of our meetings is comfortable.

We discussed about back-end technologies and definitions, as well as different areas available to focus in the spectrum,  finally  spent some time talking about reading topics and some mutual book recommendations. 

For our next session, next week Monday or Tuesday, we will cover a list of goals, previously prepared by Tung, in order to give them or identify her main priorities to focus on.

**Comment by Rabia2219** [comment]
@emecas 
Hi Emerson...the form is linked in the resources above...
