### ISSUE TITLE
IS22 Exit Interviews: Intern #2

### ISSUE THREAD

**Issue by christine-el** [hackforla/internship#274]
### Overview
We need to track the interview for Intern # 2 so that we don't drop the ball or lose data about it.

### Action Items
- [ ] Go to 1Password
  - [ ] open zoom spreadsheet
    - [ ] add time of interview and find a zoom room account that is free (zoom1-4)
- [ ] Go to the Zoom Account that you found to be free
  - [ ] Create a non recurring 1 hour meeting for that time
- [ ] Add the zoom link (from the meeting you just created) to this issue
- [ ] Add date and time to resources
- [ ] Add people (Panel to the invite) 
- [ ] Recruit a UX researcher to attend the interview 
- [ ] Add them to the invite
- [ ] Create folder for interview recording

#### Interview checklist
- [ ] 5 min prior, login to 1password and get hostkey for Zoom [Zoom meeting room#]
- [ ] Join the meeting via the calendar link in your invite or here in this issue
- [ ] Claim host
- [ ] Turn on recording and then pause
- [ ] When they enter room, ask if we can record and transcribe
- [ ] Turn on transcript, unpause recording
- [ ] Use script in interview
- [ ] upload recording and transcript and a chat file if applicable

#### Interview Recordings
  - General Folder for [candidate recordings]
  - [candidates recording](https://drive.google.com/file/d/13wa-zF7-I2iMlDPwpcqLMRIXYzF9YU7w/view?usp=sharing)

#### Interview details
- Zoom link for interview
- Date and time for interview:

#### Text once you are ready to send invite update
We have added the zoom invite info and the panelist for your interview.  Looking forward to seeing you!

**Comment by ExperimentsInHonesty** [comment]
This interview was already completed.  This issue was never filled out.  Next steps
1. Find the spreadsheet that tells you who intern #2 is
2. Find the interview recording, make sure it's in a folder for that candidate and link the text above that says `[candidates recording folder]` to the folder location URL
3. Find the [candidates folder] URL and link it
4. Add the date and time the interview was performed
5. Add who performed the interview (which UXR #)
6. Share this issue with the research lead to determine if there are more steps needed

**Comment by bradyse** [comment]
The work in this issue was completed on 07-29-22 (Elizabeth P was the interviewer). This issue is being closed and is also being tracked in:
- #319
