### ISSUE TITLE
Is SDG 16 relevant to TWE

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/internship#503]
### Overview
We need to determine if this SDG is relevant to the TWE project, so that we can align research, planing and marketing to that goal.

### Action Items
- [x] Go to Resource 1, choose the SDG indicated in the title of this issue
   - [x] Add link to that page into Resource 2
- [x] Review both targets and indicators to determine which SGS are applicable to the project.
- [x] Copy all Targets and Indicators to a comment below
   - [ ] Add notes to identify appropriate Targets/Indicators and describe how you propose to use the indicator to measure the program's progress
   - [ ] Add notes to the Targets/Indicators that you think are not a good fit and why.

### Resources/Instructions
1. https://sdgs.un.org/goals
2. [Peace, Justice & Strong Institutions](https://sdgs.un.org/goals/goal16)

**Comment by joshfishman** [comment]
Target
16.1
Significantly reduce all forms of violence and related death rates everywhere

16.1.1
Number of victims of intentional homicide per 100,000 population, by sex and age
16.1.2
Conflict-related deaths per 100,000 population, by sex, age and cause
16.1.3
Proportion of population subjected to (a) physical violence, (b) psychological violence and (c) sexual violence in the previous 12 months

16.1.4
Proportion of population that feel safe walking alone around the area they live after dark


Target
16.2
End abuse, exploitation, trafficking and all forms of violence against and torture of children

16.2.1
Proportion of children aged 1–17 years who experienced any physical punishment and/or psychological aggression by caregivers in the past month

16.2.2
Number of victims of human trafficking per 100,000 population, by sex, age and form of exploitation
16.2.3
Proportion of young women and men aged 18–29 years who experienced sexual violence by age 18


Target
16.3
Promote the rule of law at the national and international levels and ensure equal access to justice for all

16.3.1
Proportion of victims of violence in the previous 12 months who reported their victimization to competent authorities or other officially recognized conflict resolution mechanisms
16.3.2
Unsentenced detainees as a proportion of overall prison population
16.3.3
Proportion of the population who have experienced a dispute in the past two years and who accessed a formal or informal dispute resolution mechanism, by type of mechanism


Target
16.4
By 2030, significantly reduce illicit financial and arms flows, strengthen the recovery and return of stolen assets and combat all forms of organized crime

16.4.1
Total value of inward and outward illicit financial flows (in current United States dollars)
16.4.2
Proportion of seized, found or surrendered arms whose illicit origin or context has been traced or established by a competent authority in line with international instruments

Target
16.5
Substantially reduce corruption and bribery in all their forms

16.5.1
Proportion of persons who had at least one contact with a public official and who paid a bribe to a public official, or were asked for a bribe by those public officials, during the previous 12 months
16.5.2
Proportion of businesses that had at least one contact with a public official and that paid a bribe to a public official, or were asked for a bribe by those public officials during the previous 12 months

Target
16.6
Develop effective, accountable and transparent institutions at all levels

16.6.1
Primary government expenditures as a proportion of original approved budget, by sector (or by budget codes or similar)
16.6.2
Proportion of population satisfied with their last experience of public services


Target
16.7
Ensure responsive, inclusive, participatory and representative decision-making at all levels

16.7.1
Proportions of positions in national and local institutions, including (a) the legislatures; (b) the public service; and (c) the judiciary, compared to national distributions, by sex, age, persons with disabilities and population groups

16.7.2
Proportion of population who believe decision-making is inclusive and responsive, by sex, age, disability and population group

Target
16.8
Broaden and strengthen the participation of developing countries in the institutions of global governance

16.8.1
Proportion of members and voting rights of developing countries in international organizations


Target
16.9
By 2030, provide legal identity for all, including birth registration

16.9.1
Proportion of children under 5 years of age whose births have been registered with a civil authority, by age

Target
16.10
Ensure public access to information and protect fundamental freedoms, in accordance with national legislation and international agreements

16.10.1
Number of verified cases of killing, kidnapping, enforced disappearance, arbitrary detention and torture of journalists, associated media personnel, trade unionists and human rights advocates in the previous 12 months
16.10.2
Number of countries that adopt and implement constitutional, statutory and/or policy guarantees for public access to information

Target
16.a
Strengthen relevant national institutions, including through international cooperation, for building capacity at all levels, in particular in developing countries, to prevent violence and combat terrorism and crime

16.a.1
Existence of independent national human rights institutions in compliance with the Paris Principles

Target
16.b
Promote and enforce non-discriminatory laws and policies for sustainable development

16.b.1
Proportion of population reporting having personally felt discriminated against or harassed in the previous 12 months on the basis of a ground of discrimination prohibited under international human rights law

**Comment by ExperimentsInHonesty** [comment]
We are not going to add this one, because it would be difficult to explain to guardians, however, we will keep an eye on any data that might be relevant to this in the future.

This might be possible
16.3.3
Proportion of the population who have experienced a dispute in the past two years and who accessed a formal or informal dispute resolution mechanism, by type of mechanism
