### ISSUE TITLE
TWE: Revise Research: Update WIKI Template

### ISSUE THREAD

**Issue by pandanista** [hackforla/internship#534]
### Overview
We need to update the Update WIKI Template issue template so it has the same formatting as the most recent templates we have made.

### Action Items
We need to create a template issue for an Update Template, so that we can create an Update Template, when we are ready and maintain consistency with the org (across projects) and the guides project.

### Action Items
- [x] Copy the example from Resource 1.01
  - [x] Paste into a comment below using details to make it collapsible
  - [x] Use the following text for the summary
```
## Current draft of Update Issue Template
```
- [x] Copy the example from Resource 1.01
  - [x] Use the following text for the summary
```
## Revised Update Issue Template from the Guides Team
```
  - [x] Add bullet headers and divide work into sections
     - example: 
        - If the current template has
        > - [x] Go to the Google Drive, Research, 1. Research by Type, Folder
        >    - [x] Create a new folder in the drive called [number. name of type]
        - The revised template should have this text and formatting
        > - Create new Google Drive Folder
        >    - [x] Go to the Google Drive, Research, 1. Research by Type, Folder (Resource # 1.04)
        >    - [x] Create a new folder in the drive called [number. name of type] (e.g., 1. Mentor, 2. Intern) 
        >    - [x] update the link in the resources below (Resource # 2.02)
  - [x] Separate the resources into two sections
     - ```
        #### Resources for creating this issue
        ```
     - ```
        #### Resources gathered during the completion of this issue
        ```
  - [x] Make sure each resource is in order of how it appears in the instructions
  - [x] Number the resources
     - [x] Add the numbers to the action items
- [x] re-review the whole thing, to make sure 
   - [x] all the instructions make sense
   - [x] all the links resolve
   - [x] the work is listed in the most logical order
- [x] review with UX lead and get sign-off
- [ ] ask UX lead or product to update issue template Resource 1.03

### Resources/Instructions
1.01 [TWE Research: Update Issue Template, new issue](https://github.com/hackforla/internship/issues/new?assignees=&labels=feature%3A+research+audits%2C+role%3A+UI%2FUX+research%2C+size%3A+1pt&template=research--update.md&title=Update+%5BReplace+with+RP+and+the+number+e.g.%2C+RP008%5D%3A+%5Bname+of+research%5D)
1.02 [Issue templates in the code](https://github.com/hackforla/internship/tree/main/.github/ISSUE_TEMPLATE)
1.03 [TWE Research: Update Issue Template, file](https://github.com/hackforla/internship/blob/main/.github/ISSUE_TEMPLATE/research--update.md)

**Comment by pandanista** [comment]
### Overview
We need to review and update the wiki page for [Research Plan number and title] so that future HfLA volunteers can replicate our processes.

### Action Items
- [ ] Add milestone: 06.01.02 Research Audit and update wiki page
- [ ] Review/Update Research Date
- [ ] Review/Update Summary of Research
    - [ ] Update Research Question
    - [ ] Update Purpose
    - [ ] Update Methods
- [ ] Review/Update Current Status
- [ ] Search all issues to make sure that there are no mislabeled issues. 
- [ ] Make sure that the "All Issues" link correctly identifies all issues related to this RP (both open and closed)
- [ ] Review/Update Outstanding task items
- [ ] Review/Update Assets
    - [ ] Review/Update link to Research Plan
    - [ ] Review/Update link to Scripts Docs
    - [ ] If other relevant subheadings need to be created, create those headings (using RP6 as an example)
    - [ ] Review/update link to Interview Recordings & Transcripts (or relabel if it's quantitative data)
    - [ ] Review/update link to Synthesis (if nothing to report yet, leave blank)
    - [ ] Review/update link to Presentation of Findings (if nothing to report yet, leave blank)
    - [ ] Review/update link to Action Items Spreadsheet (if nothing to report yet, leave blank)
- [ ] Review/Update Links to Related Wiki Pages
- [ ]  Research lead reviews wiki page
- [ ]  Product reviews wiki page

### Resources/Instructions
- [RP__ Wiki Page]
- [Example Wiki Research Plan Page: RP6](https://github.com/hackforla/internship/wiki/Research-Plan-6:-Intern-Intake-Interviews)
- [Google Drive, Research Folder](https://drive.google.com/drive/folders/1LLHYcQCRmpC3DX_ZMj4BXNCmb_XliUXd?usp=sharing) - you can find research  plans by type or by number/name
- Don't link GitHub issues, instead make sure that the wiki page has a link to all the issues using the label (e.g., `Research: RP006` label)
- If a particular Research Plan was not conducted during the Internship 2022, note why under "Current Status".
- Tips for identifying mislabeled GitHub issues
    - In the search bar, type keywords that might be related to this research plan
    - Start broad to identify keywords that might indicate the same thing. Quickly scroll through all issues to see if the language to describe this research plan was inconsistent (e.g., "intake" vs. "onboarding"). Make sure that no matter the language that the RP label is correct.
    - Look in both open and closed issues
- [Example of Action Items Spreadsheet](https://docs.google.com/spreadsheets/d/1WGim70shHIt-6BbweDvbn-J0IdOR8JmQLYg9Rovf7bA/edit#gid=1693908723)

**Comment by pandanista** [comment]
@jinyan0425 Hi Jinyan, please follow the instructions in [the first comment](https://github.com/hackforla/internship/issues/534#issue-2094495490) and mark the checkboxes in the Action Items as you complete them.

- Please refer to #531 as an example on how it is done because it is the same instructions and structure.  
- To add formatting to any comments on GitHub, please look up Markdown language to learn some basic knowledge. 
- To make revisions or copy and paste content with the same format from another comment, select the three dot on the right hand side of the comment, and then select edit. See screenshot below.

Please let me know if you have any questions. 
<img width="700" alt="Screenshot 2024-05-02 at 11 20 02 AM" src="https://github.com/hackforla/internship/assets/57029070/e0d3da54-e152-4c05-a8b2-88951fbea5cc">

**Comment by jinyan0425** [comment]
## Current draft of Update Issue Template

### Dependencies 
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
We need to review and update the wiki page for [Research Plan number and title] so that future HfLA volunteers can replicate our processes.

### Action Items
- [ ] Add milestone: 06.01.02 Research Audit and update wiki page
- [ ] Review/Update Research Date
- [ ] Review/Update Summary of Research
    - [ ] Update Research Question
    - [ ] Update Purpose
    - [ ] Update Methods
- [ ] Review/Update Current Status
- [ ] Search all issues to make sure that there are no mislabeled issues. 
- [ ] Make sure that the "All Issues" link correctly identifies all issues related to this RP (both open and closed)
- [ ] Review/Update Outstanding task items
- [ ] Review/Update Assets
    - [ ] Review/Update link to Research Plan
    - [ ] Review/Update link to Scripts Docs
    - [ ] If other relevant subheadings need to be created, create those headings (using RP6 as an example)
    - [ ] Review/update link to Interview Recordings & Transcripts (or relabel if it's quantitative data)
    - [ ] Review/update link to Synthesis (if nothing to report yet, leave blank)
    - [ ] Review/update link to Presentation of Findings (if nothing to report yet, leave blank)
    - [ ] Review/update link to Action Items Spreadsheet (if nothing to report yet, leave blank)
- [ ] Review/Update Links to Related Wiki Pages
- [ ]  Research lead reviews wiki page
- [ ]  Product reviews wiki page

### Resources/Instructions
- [RP__ Wiki Page]
- [Example Wiki Research Plan Page: RP6](https://github.com/hackforla/internship/wiki/Research-Plan-6:-Intern-Intake-Interviews)
- [Google Drive, Research Folder](https://drive.google.com/drive/folders/1LLHYcQCRmpC3DX_ZMj4BXNCmb_XliUXd?usp=sharing) - you can find research  plans by type or by number/name
- Don't link GitHub issues, instead make sure that the wiki page has a link to all the issues using the label (e.g., `Research: RP006` label)
- If a particular Research Plan was not conducted during the Internship 2022, note why under "Current Status".
- Tips for identifying mislabeled GitHub issues
    - In the search bar, type keywords that might be related to this research plan
    - Start broad to identify keywords that might indicate the same thing. Quickly scroll through all issues to see if the language to describe this research plan was inconsistent (e.g., "intake" vs. "onboarding"). Make sure that no matter the language that the RP label is correct.
    - Look in both open and closed issues
- [Example of Action Items Spreadsheet](https://docs.google.com/spreadsheets/d/1WGim70shHIt-6BbweDvbn-J0IdOR8JmQLYg9Rovf7bA/edit#gid=1693908723)

**Comment by jinyan0425** [comment]
## Revised Update Issue Template from the Guides Team
<details><summary>Revised Update Issue Template from the Guides Team</summary>
<p>

---
**name:** 'Research: Update'
**about:** Guides you through updating the wiki with the research project info
**title:** 'Update [Replace with RP and the number e.g., RP008]: [name of research]'
**labels:** 'feature: research audits, role: UI/UX research, size: 1pt'
**assignees:**

---

### Overview
We need to review and update the wiki page for [Research Plan number and title] so that future HfLA volunteers can replicate our processes.

### Action Items
- [ ] Add milestone: 06.01.02 Research Audit and update wiki page
- [ ] Review/Update Research Date
- [ ] Review/Update Summary of Research
    - [ ] Update Research Question
    - [ ] Update Purpose
    - [ ] Update Methods
- [ ] Review/Update Current Status
- [ ] Search all issues to make sure that there are no mislabeled issues. 
- [ ] Make sure that the "All Issues" link correctly identifies all issues related to this RP (both open and closed)
- [ ] Review/Update Outstanding task items
- [ ] Review/Update Assets
    - [ ] Review/Update link to Research Plan
    - [ ] Review/Update link to Scripts Docs
    - [ ] If other relevant subheadings need to be created, create those headings (using RP6 as an example)
    - [ ] Review/update link to Interview Recordings & Transcripts (or relabel if it's quantitative data)
    - [ ] Review/update link to Synthesis (if nothing to report yet, leave blank)
    - [ ] Review/update link to Presentation of Findings (if nothing to report yet, leave blank)
    - [ ] Review/update link to Action Items Spreadsheet (if nothing to report yet, leave blank)
- [ ] Review/Update Links to Related Wiki Pages
- [ ]  Research lead reviews wiki page
- [ ]  Product reviews wiki page

### Resources/Instructions
- [RP__ Wiki Page]
- [Example Wiki Research Plan Page: RP6](https://github.com/hackforla/internship/wiki/Research-Plan-6:-Intern-Intake-Interviews)
- [Google Drive, Research Folder](https://drive.google.com/drive/folders/1LLHYcQCRmpC3DX_ZMj4BXNCmb_XliUXd?usp=sharing) - you can find research  plans by type or by number/name
- Don't link GitHub issues, instead make sure that the wiki page has a link to all the issues using the label (e.g., `Research: RP006` label)
- If a particular Research Plan was not conducted during the Internship 2022, note why under "Current Status".
- Tips for identifying mislabeled GitHub issues
    - In the search bar, type keywords that might be related to this research plan
    - Start broad to identify keywords that might indicate the same thing. Quickly scroll through all issues to see if the language to describe this research plan was inconsistent (e.g., "intake" vs. "onboarding"). Make sure that no matter the language that the RP label is correct.
    - Look in both open and closed issues
- [Example of Action Items Spreadsheet](https://docs.google.com/spreadsheets/d/1WGim70shHIt-6BbweDvbn-J0IdOR8JmQLYg9Rovf7bA/edit#gid=1693908723)

**Comment by jinyan0425** [comment]
@pandanista I need to go over the content of the revised template with you before working on the unchecked action items.

**Comment by jinyan0425** [comment]
## Revised Update Issue Template from the Guides Team
---
name: 'Research: Update'
about: Guides you through updating the wiki with the research project info
title: 'Update [Replace with RP and the number e.g., RP008]: [name of research]'
labels: 'feature: research audits, role: UI/UX research, size: 1pt'
assignees: ''

---

### Overview
We need to review and update the wiki page for [Research Plan number and title] so that future HfLA volunteers can replicate our processes.

### Action Items
- [ ] Add milestone: 06.01.02 Research Audit and update wiki page
- [ ] Review/Update Research Date
- [ ] Review/Update Summary of Research
    - [ ] Update Research Question
    - [ ] Update Purpose
    - [ ] Update Methods
- [ ] Review/Update Current Status
- [ ] Search all issues to make sure that there are no mislabeled issues. 
- [ ] Make sure that the "All Issues" link correctly identifies all issues related to this RP (both open and closed)
- [ ] Review/Update Outstanding task items
- [ ] Review/Update Assets
    - [ ] Review/Update link to Research Plan
    - [ ] Review/Update link to Scripts Docs
    - [ ] If other relevant subheadings need to be created, create those headings (using RP6 as an example)
    - [ ] Review/update link to Interview Recordings & Transcripts (or relabel if it's quantitative data)
    - [ ] Review/update link to Synthesis (if nothing to report yet, leave blank)
    - [ ] Review/update link to Presentation of Findings (if nothing to report yet, leave blank)
    - [ ] Review/update link to Action Items Spreadsheet (if nothing to report yet, leave blank)
- [ ] Review/Update Links to Related Wiki Pages
- [ ]  Research lead reviews wiki page
- [ ]  Product reviews wiki page

### Resources/Instructions
- [RP__ Wiki Page]
- [Example Wiki Research Plan Page: RP6](https://github.com/hackforla/internship/wiki/Research-Plan-6:-Intern-Intake-Interviews)
- [Google Drive, Research Folder](https://drive.google.com/drive/folders/1LLHYcQCRmpC3DX_ZMj4BXNCmb_XliUXd?usp=sharing) - you can find research  plans by type or by number/name
- Don't link GitHub issues, instead make sure that the wiki page has a link to all the issues using the label (e.g., `Research: RP006` label)
- If a particular Research Plan was not conducted during the Internship 2022, note why under "Current Status".
- Tips for identifying mislabeled GitHub issues
    - In the search bar, type keywords that might be related to this research plan
    - Start broad to identify keywords that might indicate the same thing. Quickly scroll through all issues to see if the language to describe this research plan was inconsistent (e.g., "intake" vs. "onboarding"). Make sure that no matter the language that the RP label is correct.
    - Look in both open and closed issues
- [Example of Action Items Spreadsheet](https://docs.google.com/spreadsheets/d/1WGim70shHIt-6BbweDvbn-J0IdOR8JmQLYg9Rovf7bA/edit#gid=1693908723)

**Comment by jinyan0425** [comment]
This is ready to review @pandanista. I will make any revisions and edits as needed. 

A few comments: 

1. According to our discussion, I titled the template "Update Wiki Page Template" instead of "Revised Update Issue Template from the Guides Team" in the first comment. Shall we further change it to "Research Audit and Update Wiki Template" to be consistent with the name of the milestone?

2. I am not sure about the last two action items? I assume they mean to ask the research lead and product team to review the wiki page. 
     - [ ] Research Lead Reviews Wiki Page
     - [ ]  Product Reviews Wiki Page

3. I did not find a good example of action item spreadsheet. The example provided in the old template is [hackforla.org: RP009: Action Steps- Wins Page Research](https://docs.google.com/spreadsheets/d/1WGim70shHIt-6BbweDvbn-J0IdOR8JmQLYg9Rovf7bA/edit#gid=1693908723). Not sure how good it is. So, I did not add details as I did for other actions.

4. As for the order of the actions, is it possible to update all the labels including milestones at the end? The label information (e.g., participant type) may be clearer after researchers have reviewed and updated the wiki page. 

5. I added more details, compared to the original template.

6. Two minor changes: I renamed "06.01.02 Research Audit and update wiki page" to "06.01.02 Research Audit and Update Wiki Page", and "Research Plan # and name" to "Research Plan # and Name" in Google Drive. I am a bit obsessive-compulsive about capitalization for consistency.

**Comment by pandanista** [comment]
- Did you accidentally delete a comment? 
    - I remember there were three comments: old template, new template from the guide team, and updated template for TWE.
    - Looks like the new template from the guide team is missing?
    - We usually hide comments as they are outdated or not relevant anymore, but not delete them.

-is [this comment](https://github.com/hackforla/internship/issues/534#issuecomment-2111322543) the updated template? If so, let's not collapse it so it is easier for review.

**Comment by pandanista** [comment]
> This is ready to review @pandanista. I will make any revisions and edits as needed.
> 
> A few comments:
> 
> 1. According to our discussion, I titled the template "Update Wiki Page Template" instead of "Revised Update Issue Template from the Guides Team" in the first comment. Shall we further change it to "Research Audit and Update Wiki Template" to be consistent with the name of the milestone?
    - We could do that. Let's confirm with the Product team before making that change.
    - The alternative would be to add research audit to the overview section so anyone assigned would be clear about the goal and process of the issue.
> 2. I am not sure about the last two action items? I assume they mean to ask the research lead and product team to review the wiki page.
>    
>    * [ ]  Research Lead Reviews Wiki Page
>    * [ ]   Product Reviews Wiki Page
    - Yes, it is for the review process before any issue gets closed.
> 3. I did not find a good example of action item spreadsheet. The example provided in the old template is [hackforla.org: RP009: Action Steps- Wins Page Research](https://docs.google.com/spreadsheets/d/1WGim70shHIt-6BbweDvbn-J0IdOR8JmQLYg9Rovf7bA/edit#gid=1693908723). Not sure how good it is. So, I did not add details as I did for other actions.
    - We have a template, and let me grab it for you.
> 4. As for the order of the actions, is it possible to update all the labels including milestones at the end? The label information (e.g., participant type) may be clearer after researchers have reviewed and updated the wiki page.
    - We want to keep it consistent across all issues since all the issues have the customizations for labels and milestone at the top.
> 5. I added more details, compared to the original template.
    - Great.
> 6. Two minor changes: I renamed "06.01.02 Research Audit and update wiki page" to "06.01.02 Research Audit and Update Wiki Page", and "Research Plan # and name" to "Research Plan # and Name" in Google Drive. I am a bit obsessive-compulsive about capitalization for consistency.
    - Thank you for being detail-oriented.

**Comment by jinyan0425** [comment]
> * Did you accidentally delete a comment?
>   
>   * I remember there were three comments: old template, new template from the guide team, and updated template for TWE.
>   * Looks like the new template from the guide team is missing?
>   * We usually hide comments as they are outdated or not relevant anymore, but not delete them.
> 
> -is [this comment](https://github.com/hackforla/internship/issues/534#issuecomment-2111322543) the updated template? If so, let's not collapse it so it is easier for review.

Sorry that I misunderstood it. Yes, I deleted an earlier comment which was the older version of the revised template. I assumed I should finish the revised template based on the demo. I did not realize that we should keep the "Revised Update Issue Template from the Guides Team". I could redo the two comments in the correct order, but this requires deleting the comment on the current revised template--might not be ideal.

**Comment by ExperimentsInHonesty** [comment]
Product needs to review the [template in comment above](https://github.com/hackforla/internship/issues/534#issuecomment-2111322543) for the ordering of resources

**Comment by jinyan0425** [comment]
> @jinyan0425: To answer some comments you had earlier,
> 
> 1. According to our discussion, I titled the template "Update Wiki Page Template" instead of "Revised Update Issue Template from the Guides Team" in the first comment. Shall we further change it to "Research Audit and Update Wiki Template" to be consistent with the name of the milestone?
>    
>    * We could do that. Let's confirm with the Product team before making that change.
>    * The alternative would be to add research audit to the overview section so anyone assigned would be clear about the goal and process of the issue.
> 2. I am not sure about the last two action items? I assume they mean to ask the research lead and product team to review the wiki page.
> 
> > * [ ]   Research Lead Reviews Wiki Page
> > * [ ]    Product Reviews Wiki Page
> 
> * Yes, it is for the review process before any issue gets closed.
> 
> 1. I did not find a good example of action item spreadsheet. The example provided in the old template is [hackforla.org: RP009: Action Steps- Wins Page Research](https://docs.google.com/spreadsheets/d/1WGim70shHIt-6BbweDvbn-J0IdOR8JmQLYg9Rovf7bA/edit#gid=1693908723). Not sure how good it is. So, I did not add details as I did for other actions.
>    
>    * We have a template, and let me grab it for you.
>    * [the template for action item](https://docs.google.com/spreadsheets/d/1BFmVBkkuRvDgBZkumXr5FPiLgdyPgr1KFUZ0rBTUsw0/edit?usp=share_link)
> 2. As for the order of the actions, is it possible to update all the labels including milestones at the end? The label information (e.g., participant type) may be clearer after researchers have reviewed and updated the wiki page.
>    
>    * We want to keep it consistent across all issues since all the issues have the customizations for labels and milestone at the top.
> 3. I added more details, compared to the original template.
>    
>    * Great.
> 4. Two minor changes: I renamed "06.01.02 Research Audit and update wiki page" to "06.01.02 Research Audit and Update Wiki Page", and "Research Plan # and name" to "Research Plan # and Name" in Google Drive. I am a bit obsessive-compulsive about capitalization for consistency.
>    
>    * Thank you for being detail-oriented.

Thanks! I just updated the details about the ```action item spreadsheet```. @pandanista

**Comment by pandanista** [comment]
@jinyan0425 Thank you so much for all the work you have put into revising the template! I edited a few minor things, but it looks great overall.

**Comment by jinyan0425** [comment]
> @jinyan0425 Thank you so much for all the work you have put into revising the template! I edited a few minor things, but it looks great overall.

Thanks for your edits :)

**Comment by ExperimentsInHonesty** [comment]
Product needs to Re-review the resources to make sure the links are all matching what the test is, when they are mentioned in the action items.
e.g., Resource 1.01 points to the research folder, not the plan # folder.

**Comment by pandanista** [comment]
- Closing this issue as the Update Wiki Page template in [this comment](https://github.com/hackforla/internship/issues/534#issuecomment-2111322543) is sufficient for our purpose to reorganize the list of resources for now.  
- #593 is created to further update the Update wiki page template.
