### ISSUE TITLE
TWE Design System Components: Update Input field according to M3

### ISSUE THREAD

**Issue by karina-sato** [hackforla/internship#540]
### Overview
We need to update the components to match M3 Material Design guidelines style

### Action Items
- [x] Use M3 Material Design guidelines to assess the style differences
- [x] Update the component design
- [x] Communicate changes in the issue's comments and with the design team
- [x] Update/create microsite for devs accordingly
- [ ] Get sign-off from Project Manager
- [x] Add the microsite to the "Ready for Dev" page
- [ ] Close this issue
- [ ] Release Dependency on https://github.com/hackforla/internship/issues/409 and if it is the last dependency to get released, move issue to the new issue approval column & add the `ready for design lead` label

### Resources/Instructions
- Use Material Design (https://m3.material.io/) as guideline

**Comment by meetminji** [comment]
disabled grey too light, switch to color "grey" and close issue

**Comment by karina-sato** [comment]
Thank you @meetminji. Can you also create the microsite for the dev team? In the next team meeting, you can present the microsite to get sign off and close the issue.

**Comment by karina-sato** [comment]
Hi @meetminji 
Can you add your updates here? 
If you're finished, can you please add links to the master component + microsite, unassign yourself from this issue, tag "Ready for dev lead", and move the issue to the Question/Review column?

**Comment by meetminji** [comment]
https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=5186-4811&mode=design&t=xWuRqnxufhaJDP75-0

<img width="534" alt="Screen Shot 2024-03-28 at 9 48 37 AM" src="https://github.com/hackforla/internship/assets/98001179/63cfc102-3b86-4073-a7ec-fabe770373f3">
<img width="597" alt="Screen Shot 2024-03-28 at 9 48 52 AM" src="https://github.com/hackforla/internship/assets/98001179/36ccd611-86d9-45c7-96e6-60630a6606aa">

**Comment by meetminji** [comment]
- [ ] Disabled should be darker. Check with accessibility.
- [ ] plugin for measurement on figma @karina-sato 
- [ ] microsite: put right arrow icon on class section if it does not fit in container

**Comment by meetminji** [comment]
**Changed disabled colors and passed accessibility test:**

<img width="130" alt="input field disabled" src="https://github.com/hackforla/internship/assets/98001179/a444f6af-46ef-4daa-a48a-3b9a31257b20">

**Microsite ready for dev:**

<img width="459" alt="input field mircrosite" src="https://github.com/hackforla/internship/assets/98001179/5deb131d-3fde-472d-b855-3ab224180809">

but had some issues with spec measurements

**Comment by meetminji** [comment]
Specs ready to go


<img width="570" alt="input fields - specs" src="https://github.com/hackforla/internship/assets/98001179/64d30704-4742-4b21-99e1-593f4a976321">

**Comment by ExperimentsInHonesty** [comment]
Add a background color specification for the input fields

**Comment by meetminji** [comment]
https://m2.material.io/design/color/dark-theme.html#properties

A dark theme uses dark grey, rather than black

<img width="758" alt="Screen Shot 2024-04-15 at 2 02 08 PM" src="https://github.com/hackforla/internship/assets/98001179/b50b9378-275e-40e0-b4e4-393c50c6112d">

<img width="577" alt="Screen Shot 2024-04-15 at 2 04 07 PM" src="https://github.com/hackforla/internship/assets/98001179/ab53e843-28e9-414a-bde8-51e4de8f6112">
16% is the highest elevation level

<img width="593" alt="Screen Shot 2024-04-15 at 2 07 57 PM" src="https://github.com/hackforla/internship/assets/98001179/d2914d67-2bf0-45c8-bdf3-75ac45af254f">

<img width="586" alt="Screen Shot 2024-04-15 at 2 08 44 PM" src="https://github.com/hackforla/internship/assets/98001179/576a214f-1cb6-4377-a71c-5ef2996f328d">

**Comment by meetminji** [comment]
<img width="875" alt="input field - dark mode" src="https://github.com/hackforla/internship/assets/98001179/b12bd2e5-d688-4b24-9873-92eaa5c90feb">

**Comment by meetminji** [comment]
for picking other colors


https://m2.material.io/design/color/the-color-system.html#tools-for-picking-colors

**Comment by meetminji** [comment]
TWE Colors for Dark Mode

<img width="169" alt="Screen Shot 2024-04-24 at 2 19 32 PM" src="https://github.com/hackforla/internship/assets/98001179/8dedea3e-2c24-479a-b899-e95da3ee8b28">

**Comment by meetminji** [comment]
dark mode for v2

**Comment by ExperimentsInHonesty** [comment]
@meetminji are we ready to close this issue, or do you need feedback from Dev first?

**Comment by joshfishman** [comment]
@meetminji  just needs new disabled colors. Thanks

**Comment by meetminji** [comment]
disabled updated:
background light gray
text dark gray
pass through **38% opacity**

<img width="131" alt="Input Field Disabled" src="https://github.com/hackforla/internship/assets/98001179/64424144-1a8c-4cf3-9ed4-5a002837c

<img width="827" alt="Input Field Disabled details" src="https://github.com/hackforla/internship/assets/98001179/f43ff40d-1974-4076-907f-f53a0a5af6b1">
b0d">

**Comment by ExperimentsInHonesty** [comment]
@joshfishman please review - Minji answered your request.

**Comment by mklmrgn** [comment]
Layout of these need to be changed to be more responsive in order to be used inside of other components (forms, cards, dialogs, etc).

**Comment by mklmrgn** [comment]
**Updated text fields to be responsive and modular (width) in order to work with new components.** 
![Screen Shot 2024-09-12 at 9 54 07 AM](https://github.com/user-attachments/assets/3f056468-a0d0-47c8-96c5-ea321b9a4451)

**Added important states that are part of M3, such as Populated vs Unpopulated**
![Screen Shot 2024-09-12 at 9 51 43 AM](https://github.com/user-attachments/assets/62386068-eb46-42a3-8e5e-0d6565e093c9)

**Changed**
![Screen Shot 2024-09-12 at 9 57 25 AM](https://github.com/user-attachments/assets/c39c7492-dabc-453d-bad6-8e5d0932eee0)
 from individual components to variants to make changing states easier for designers

**Comment by ExperimentsInHonesty** [comment]
@mklmrgn I am going to unassign Josh from this issue.

**Comment by mklmrgn** [comment]
Updated Microsite to reflect changes to component (populated vs unpopulated states, class names)
<br>
**OLD**
![Image](https://github.com/user-attachments/assets/61bcdfcf-2f65-4789-b614-a65679645135)
<br>
**NEW**
![Image](https://github.com/user-attachments/assets/13dc9e6f-43bd-4072-ba9b-213530572df8)

<br>
Issue is ready for Sign Off

**Comment by sunannie27** [comment]
@joshfishman Product approval, waiting for dev feedback.

**Comment by joshfishman** [comment]
ready to move to dev thank you!
