### ISSUE TITLE
TWE Design System Components: Create shadow styles according to M3

### ISSUE THREAD

**Issue by karina-sato** [hackforla/internship#541]
### Overview
We need to create the shadow styles according to M3 to be used consistently in different components of our Design System 

### Action Items
- [x] Use M3 Material Design guidelines to assess the style differences
- [x] Create the different levels and styles according to M3 and name them accordingly
- [x] Communicate changes in the issue's comments and with the design team
- [ ] Close this issue

### Resources/Instructions
- Use Material Design (https://m3.material.io/) as guideline

**Comment by karina-sato** [comment]
Great @mklmrgn, tysm! Can you also create a microsite similar to the template below? We can have the different levels of elevations in Class. We don't need states, so instead, we can have Use Case and Examples of when to each. 

<img width="501" alt="image" src="https://github.com/hackforla/internship/assets/140572674/6deb9914-c352-43e9-9e54-b638541f76b9">

**Comment by karina-sato** [comment]
@mklmrgn update your progress here. If you are finished, add comment with updates and link to the master component + microsite. Unassign yourself, add tag "Ready for dev", move the issue to the question and review column. Don't forget to mark the Action Items.

**Comment by mklmrgn** [comment]
Created Elevation shadow styles according to Material 3's style guide. Created a brief overview of how to use perceived elevation for UI. Defined different drop shadows for each elevation (i.e. level 1, level 2, etc) in order to have standardized way to create elevation effect using shadows. 

Links to [Style in Design System ](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=4764%3A3549&mode=design&t=Zh68ukr4pT6pyPcb-1) and [Microsite](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=4785%3A805&mode=design&t=Zh68ukr4pT6pyPcb-1)

<img width="657" alt="Screen Shot 2024-03-14 at 9 53 37 AM" src="https://github.com/hackforla/internship/assets/81997978/771a2ca2-399e-4876-8ff6-3caebe8f6ba3">

**Comment by joshfishman** [comment]
approved thank you!
